---
description: 
images:
  - "socialmedia2.png"

geekdocToC: 3
geekdocTagsToMenu: true

geekdocRepo: https://github.com/Tropicraft/info.tropicraft.net
geekdocEditPath: edit/main

geekdocSearch: true
geekdocSearchShowParent: true

# geekdocLegalNotice: https://thegeeklab.de/legal-notice/#contact-information
# geekdocPrivacyPolicy: https://thegeeklab.de/legal-notice/#privacy-policy

geekdocImageLazyLoading: true
# geekdocDarkModeDim: false
