name: Hugo Build

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  build-site:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.92.2'
          # extended: true

      - name: Build Site
        run: hugo --minify --verbose
